### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by shu-doun** [shu-doun/protospace-35268#1]
#URL
https://protospace-35268.herokuapp.com/

**Comment by takumi0530** [comment]
@shu-doun さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [ ] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像およびプロトタイプ名をクリックすると、該当するプロトタイプの詳細ページへ遷移すること**

- [ ] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること**

現状、2パターンの修正点がございます。

1. ログイン状態でもログアウト状態でも、一覧表示されているプロトタイプ名をクリックで該当詳細画面に遷移できません。
2. ログアウト状態ですと一覧表示されているプロトタイプから各詳細画面に遷移できません。（ログイン画面に遷移してしまいます。）

**※上記により、ログアウト状態での動作確認が全て完了しておりません。次回ご提出時に併せて確認させていただきます。**

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by shu-doun** [comment]
修正を行いました。挙動確認をお願いします。

**Comment by takumi0530** [comment]
@shu-doun さん、再度ご提出ありがとうございます‼︎
動作の確認をしたところ、前回の点は修正が確認できましたが、今回新たに修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [ ] **ログアウト状態のユーザーは、プロトタイプ新規投稿ページ・プロトタイプ編集ページに遷移しようとすると、ログインページにリダイレクトされること**
現状、編集ページのURLを直接打ち込むと、エラーページに遷移してしまいます。
<img width="655" alt="スクリーンショット 2021-04-19 10 18 27" src="https://user-images.githubusercontent.com/76197191/115169418-e6d53c80-a0f8-11eb-98a0-9cc60e5c74e5.png">


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by shu-doun** [comment]
修正をしたので、レビューをお願いします。

**Comment by takumi0530** [comment]
@shu-doun さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
